
# This file was *autogenerated* from the file streamline.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
var('x y')
p1 = streamline_plot((y, -x), (x, -_sage_const_2 , _sage_const_2 ), (y, -_sage_const_2 , _sage_const_2 ), color=(_sage_const_0 ,_sage_const_0 ,_sage_const_0 ))
p2 = plot_vector_field((y, -x), (x, -_sage_const_2 , _sage_const_2 ), (y, -_sage_const_2 , _sage_const_2 ), color=(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ))
P = p1 + p2
P.save('streamline.png')



