
# This file was *autogenerated* from the file HW.1.5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p5 = RealNumber('0.5')
var('y')
__tmp__=var("y"); f = symbolic_expression(y**_sage_const_3 ).function(y)
y0=_sage_const_1 
deltaT=_sage_const_0p5 
steps=_sage_const_2 
eulerData = [[k*deltaT,y0] for k in range(_sage_const_0 ,steps+_sage_const_1 )]
for k in (ellipsis_range(_sage_const_1 ,Ellipsis,steps)):
    eulerData[k][_sage_const_1 ] = eulerData[k-_sage_const_1 ][_sage_const_1 ] + deltaT*f(eulerData[k-_sage_const_1 ][_sage_const_1 ])

table(eulerData)

