
# This file was *autogenerated* from the file HW.1.3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5)
var('y t')
a = plot_slope_field(-y+t+_sage_const_1 ,(y, -_sage_const_5 , _sage_const_5 ), (t, -_sage_const_5 , _sage_const_5 ))
a.show()
a.save("HW.1.3_1.a.png")

