
# This file was *autogenerated* from the file HW2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_28p24858 = RealNumber('28.24858'); _sage_const_8p8 = RealNumber('8.8'); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12); _sage_const_0p3 = RealNumber('0.3'); _sage_const_10 = Integer(10); _sage_const_0p5 = RealNumber('0.5')
var('x y z')
var('max')
max=_sage_const_0p5 
disk = plot(((_sage_const_0p5 *_sage_const_10 **-_sage_const_9 )/(_sage_const_2 *(_sage_const_8p8 *_sage_const_10 **(-_sage_const_12 ))))*(_sage_const_1 -(_sage_const_1 +(_sage_const_0p3 **_sage_const_2 /z**_sage_const_2 ))**(-_sage_const_1 )), (z, _sage_const_0 , max), gridlines=True)
sheet = plot(_sage_const_28p24858 , (z, _sage_const_0 , max), color='red')
disk = disk + sheet
disk.save("Plots.png")

