
# This file was *autogenerated* from the file 1_e.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_2p5 = RealNumber('2.5'); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_80 = Integer(80); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p75 = RealNumber('0.75'); _sage_const_105 = Integer(105); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_30 = Integer(30); _sage_const_55 = Integer(55)
from sage.plot.colors import rgbcolor
def coef(k):
    if k % _sage_const_2  == _sage_const_0 :
        return prod(((n+_sage_const_1 )*(n-_sage_const_4 ))/(n*(n-_sage_const_1 )) for n in range(_sage_const_2 , k+_sage_const_2 , _sage_const_2 ))
    else:
        return prod(((n+_sage_const_1 )*(n-_sage_const_4 ))/(n*(n-_sage_const_1 )) for n in range(_sage_const_3 , k+_sage_const_2 , _sage_const_2 ))

def gen_eq(r):
    return _sage_const_1  + (-_sage_const_3 )*pow(x, _sage_const_2 )+x+sum([coef(k) * pow(x, k) for k in range(_sage_const_3 , r+_sage_const_2 , _sage_const_2 )])

__tmp__=var("x"); f = symbolic_expression(_sage_const_1  + (-_sage_const_3 )*pow(x, _sage_const_2 ) + x + sum([coef(k) * pow(x, k) for k in range(_sage_const_3 , _sage_const_7 , _sage_const_2 )])).function(x)
plt = plot(gen_eq(_sage_const_5 ), (x, -_sage_const_2p5 , _sage_const_1p5 ), ymax=_sage_const_5 , ymin=-_sage_const_5 , color=rgbcolor((_sage_const_0 , _sage_const_0 , _sage_const_1 )))
plt += plot(gen_eq(_sage_const_30 ), (x, -_sage_const_2p5 , _sage_const_1p5 ), ymax=_sage_const_5 , ymin=-_sage_const_5 , color=rgbcolor((_sage_const_0p25 , _sage_const_0 , _sage_const_0p75 )))
plt += plot(gen_eq(_sage_const_55 ), (x, -_sage_const_2p5 , _sage_const_1p5 ), ymax=_sage_const_5 , ymin=-_sage_const_5 , color=rgbcolor((_sage_const_0p5 , _sage_const_0 , _sage_const_0p5 )))
plt += plot(gen_eq(_sage_const_80 ), (x, -_sage_const_2p5 , _sage_const_1p5 ), ymax=_sage_const_5 , ymin=-_sage_const_5 , color=rgbcolor((_sage_const_0p75 , _sage_const_0 , _sage_const_0p25 )))
plt += plot(gen_eq(_sage_const_105 ), (x, -_sage_const_2p5 , _sage_const_1p5 ), ymax=_sage_const_5 , ymin=-_sage_const_5 , color=rgbcolor((_sage_const_1 , _sage_const_0 , _sage_const_0 )))
plt.save("1_e.png")

